### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by r4sas** [PurpleI2P/pyseeder#2]
> Traceback (most recent call last):
>   File "pyseeder.py", line 112, in <module>
>     main()
>   File "pyseeder.py", line 103, in main
>     args.func(args)
>   File "/srv/pyseeder/pyseeder/actions.py", line 27, in reseed
>     su3file.write(args.outfile, args.private_key, priv_key_password)
>   File "/srv/pyseeder/pyseeder/su3file.py", line 51, in write
>     pyseeder.crypto.append_signature(filename, priv_key, priv_key_password)
>   File "/srv/pyseeder/pyseeder/crypto.py", line 69, in append_signature
>     signature = private_key.sign(contents, padding.PKCS1v15(), hashes.SHA512())
>   File "/srv/pyseeder/venv/lib/python3.4/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 617, in sign
>     signature = signer.finalize()
>   File "/srv/pyseeder/venv/lib/python3.4/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 230, in finalize
>     return self._finalize_method(evp_md)
>   File "/srv/pyseeder/venv/lib/python3.4/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 285, in _finalize_pkey_ctx
>     assert errors[0].lib == self._backend._lib.ERR_LIB_RSA
> IndexError: list index out of range
> 

Это если конвертировать сертификат из джавовского кейстора в pem. Видимо каких то параметров ключа ему не хватает.

**Comment by l-n-s** [comment]
I need java keystore to reproduce. Currently, don't have enough bandwidth to DL java, maybe later.

**Comment by r4sas** [comment]
Я же сказал тебе, попробуй спросить разработчиков cryptography.

**Comment by r4sas** [comment]
https://trac.i2p2.de/ticket/2005
